package com.github.nounitheodora.uxsniffer.report;

import com.github.nounitheodora.uxsniffer.quality.CostMapper;
import com.github.nounitheodora.uxsniffer.scanner.SmellFinding;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.testFramework.ServiceContainerUtil;
import com.intellij.testFramework.fixtures.BasePlatformTestCase;

import java.util.List;

public class HtmlReportExporterTest extends BasePlatformTestCase {

    @Override
    protected void setUp() throws Exception {
        super.setUp();
        ServiceContainerUtil.registerServiceInstance(
                ApplicationManager.getApplication(), CostMapper.class, new CostMapper());
    }

    public void testGenerate_emptyFindings() {
        String html = HtmlReportExporter.generate(List.of(), "TestProject", "/base");
        assertTrue(html.contains("<!DOCTYPE html>"));
        assertTrue(html.contains("TestProject"));
        assertTrue(html.contains("Total Smells"));
        assertTrue(html.contains("0"));
    }

    public void testGenerate_containsProjectName() {
        String html = HtmlReportExporter.generate(List.of(), "MyVueApp", "/base");
        assertTrue(html.contains("MyVueApp"));
    }

    public void testGenerate_containsSmellName() {
        SmellFinding finding = new SmellFinding(
                "Large file", "/base/src/App.vue", "App.vue", "File has 300 lines");
        String html = HtmlReportExporter.generate(List.of(finding), "P", "/base");
        assertTrue(html.contains("Large file"));
        assertTrue(html.contains("App.vue"));
        assertTrue(html.contains("File has 300 lines"));
    }

    public void testGenerate_containsChartJs() {
        String html = HtmlReportExporter.generate(List.of(), "P", "/base");
        assertTrue(html.contains("chart.js") || html.contains("Chart"));
    }

    public void testGenerate_containsFooter() {
        String html = HtmlReportExporter.generate(List.of(), "P", "/base");
        assertTrue(html.contains("Generated by"));
        assertTrue(html.contains("UXSniffer"));
    }

    public void testGenerate_multipleFindings() {
        List<SmellFinding> findings = List.of(
                new SmellFinding("Large file", "/base/A.vue", "A.vue", "msg1"),
                new SmellFinding("Too many props", "/base/B.vue", "B.vue", "msg2"),
                new SmellFinding("Any type usage", "/base/C.vue", "C.vue", "msg3")
        );
        String html = HtmlReportExporter.generate(findings, "P", "/base");
        assertTrue(html.contains("Large file"));
        assertTrue(html.contains("Too many props"));
        assertTrue(html.contains("Any type usage"));
        assertTrue(html.contains("A.vue"));
        assertTrue(html.contains("B.vue"));
        assertTrue(html.contains("C.vue"));
    }

    public void testGenerate_containsCostSection() {
        SmellFinding finding = new SmellFinding(
                "Large file", "/base/A.vue", "A.vue", "msg");
        String html = HtmlReportExporter.generate(List.of(finding), "P", "/base");
        assertTrue(html.contains("Internal Failure") || html.contains("Appraisal"));
    }

    public void testGenerate_specialCharactersEscaped() {
        SmellFinding finding = new SmellFinding(
                "Large file", "/base/A.vue", "A.vue", "msg with <script> & \"quotes\"");
        String html = HtmlReportExporter.generate(List.of(finding), "P", "/base");
        assertNotNull(html);
        assertTrue(html.contains("<!DOCTYPE html>"));
    }

    public void testGenerate_relativePathInTable() {
        SmellFinding finding = new SmellFinding(
                "Large file", "/project/root/src/views/Dashboard.vue", "Dashboard.vue", "msg");
        String html = HtmlReportExporter.generate(List.of(finding), "P", "/project/root");
        assertTrue(html.contains("src/views/Dashboard.vue"));
    }

    public void testGenerate_smellCountsCorrect() {
        List<SmellFinding> findings = List.of(
                new SmellFinding("Large file", "/base/A.vue", "A.vue", "msg"),
                new SmellFinding("Large file", "/base/B.vue", "B.vue", "msg"),
                new SmellFinding("Large file", "/base/C.vue", "C.vue", "msg")
        );
        String html = HtmlReportExporter.generate(findings, "P", "/base");
        assertTrue(html.contains("3"));
    }
}